version: "3"

volumes:
  postgres_data:

services:
  database:
    image: postgres:latest
    container_name: msm-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: my-sales-manager
      POSTGRES_USER: msm
      POSTGRES_PASSWORD: msm
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: my-sales-manager-api
    container_name: msm-api
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://msm:msm@database:5432/my-sales-manager
    depends_on:
      - database

  web:
    image: my-sales-manager-web
    container_name: msm-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        REACT_APP_API_URL: http://api:3000

    restart: always
    ports:
      - 3001:80
    depends_on:
      - api
